### ISSUE TITLE
Recursion error while parsing gtf

### ISSUE THREAD

**Issue by PedroBarbosa** [openvax/gtfparse#17]
Hello @iskandr ,

I'm trying to extract canonical transcripts from human gencode gtf, but i'm not able to create the initial dataframe with this package.

Any help?

```
Traceback (most recent call last):
  File "extract_canonical_transcripts.py", line 39, in <module>
    main()
  File "extract_canonical_transcripts.py", line 37, in main
    read_gtf(args.gtf_file)
  File "extract_canonical_transcripts.py", line 15, in read_gtf
    df = read_gtf(gtf)
  File "extract_canonical_transcripts.py", line 15, in read_gtf
    df = read_gtf(gtf)
  File "extract_canonical_transcripts.py", line 15, in read_gtf
    df = read_gtf(gtf)
  [Previous line repeated 995 more times]
RecursionError: maximum recursion depth exceeded
```
Best,
Pedro

**Comment by iskandr** [comment]
Well that's a first -- I don't think there are any recursive functions in this package (though my memory may be failing me). 

Can you send me a minimal but complete example of this happening? Also, is there any chance you're passing a callback function which is causing a recursive loop?

**Comment by PedroBarbosa** [comment]
Hi,

Sorry for the late response, I forgot to answer. It was solved in the day. Indeed, i was passing a callback function :/

Best,
