### ISSUE TITLE
No module named 'gtfparse.attribute_parsing'

### ISSUE THREAD

**Issue by tamlupwhy** [openvax/gtfparse#48]
I am using gtfparse whose version is 1.2.1 on windows, but I met an error when importing it, how can I do to solve this problem?

```
>>> import gtfparse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramData\anaconda3\envs\stereopy-130\lib\site-packages\gtfparse\__init__.py", line 13, in <module>
    from .attribute_parsing import expand_attribute_strings
ModuleNotFoundError: No module named 'gtfparse.attribute_parsing'
```

by the way , with the same version on linux, this error does not occur.

**Comment by tamlupwhy** [comment]
Forcing to reinstall can solve this problem.
